//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class EmployeeDetail : INotifyPropertyChanged
    {
        private int id;
        private string name;
        private string age;
        private string gender;
        private string address;
        public int Id { get=>id; set
            {
                id = value;
                OnPropertyChanged(nameof(Id));
            }
        }
        public string Name { get=>name; set {
                name = value;
                OnPropertyChanged(nameof(Name));
            } }
        public string Age { get=>age; set
            {
                age = value;
                OnPropertyChanged(nameof(Age));
            }
            }
        public string Gender { get=>gender; set
            {
                gender = value;
                OnPropertyChanged(nameof(Gender));
            } }
        public string Address { get=>address; set
            {
                address = value;
                OnPropertyChanged(nameof(Address));
            } }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string propertyName=null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
